---
development:
  # Application
  API_HOST: http://localhost:9090

test:
  # Application
  API_HOST: http://localhost:9090

app_test:
  # Application
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9090

production:
  # API_HOST: https://mind-map.herokuapp.com
