---
development:
  # Application
  API_HOST: http://localhost:9090

test:
  # Application
  API_HOST: http://localhost:9090

app_test:
  # Application
  APP_HOST: http://localhost:9000
  API_HOST: http://localhost:9090

production:
  APP_HOST: https://mytest-app-mind-map.herokuapp.com
  API_HOST: https://mytest-api-mind-map.herokuapp.com
