---
development:
  # Application
  API_HOST: http://localhost:9000

test:
  # Application
  API_HOST: http://localhost:9000

app_test:
  # Application
  API_HOST: http://localhost:9000

production:
  # API_HOST: https://mind-map.herokuapp.com